name: Code Coverage with Coveralls

on:
  push:
    branches:
      - main

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    env:
      REPO: starbops
      MANAGER: virtbmc-controller
      AGENT: virtbmc
      VERSION: ${{ github.event.pull_request.head.ref }}-head
      GIT_COMMIT: ${{ github.sha }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Lint
        run: make lint

      - name: Run tests with coverage
        run: make test 

      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: Upload coverage to Coveralls
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }} 
        run: goveralls -coverprofile=cover.out -service=github